### Get all expenses with default limit and offset

GET http://localhost:3000/api/expenses

### Get all expenses with limit and page

GET http://localhost:3000/api/expenses?limit=10&page=2

### Get all expenses with limit, page and sort by date

GET http://localhost:3000/api/expenses?limit=10&page=2&sort=date

### Get all expenses with limit, page and sort by amount

GET http://localhost:3000/api/expenses?limit=10&page=2&sort=amount


### Get expenses in a date range
GET http://localhost:3000/api/expenses?from=2023-12-01&to=2023-12-31

### Get expenses in an amount range
GET http://localhost:3000/api/expenses?amountFrom=100&amountTo=200


### Get one expense by id
GET http://localhost:3000/api/expenses/1

### Delete one expense by id
DELETE http://localhost:3000/api/expenses/1

### Update one expense by id
PUT http://localhost:3000/api/expenses/1
Content-Type: application/json
Accept: application/json

{
    "amount": 100,
    "description": "Updated description",
    "recipient": "Updated recipient",
    "category": "Updated category",
    "date": "2023-12-31"
}
